name: shell
version: 2.0.0
homepage: https://github.com/thosakwe/shell.git
author: Tobe Osakwe <thosakwe@gmail.com>
description: Wrapper over `dart:io` [Process] API's that supports additional features.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  file: ^6.1.2
  path: ^1.8.0
  platform: ^3.0.0
  process: ^4.2.3
